image: gitlab-registry.cern.ch/industrial-controls/sw-infra/jenkins/mvn-plus-jdk

stages:
  - build
  - deploy
  - sonar

# Get the settings file from c2mon project
before_script:
  - curl -L -O https://cern.ch/maven/settings-ci.xml

# Fully build and publish master branch
build_and_publish:
  stage: deploy
  script:
    - mvn -B deploy --settings settings-ci.xml
  only:
    - tags
    - develop

# Just run tests on feature branches
build:
  stage: build
  script:
    - mvn -B test --settings settings-ci.xml
  except:
    - master

sonar_preview:
  type: sonar
  script:
    - mvn -B compile sonar:sonar -Ddependencies.set.all -Dmaven.test.skip=true -Djavax.net.ssl.trustStore=${CACERTS} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings-ci.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  script:
    - mvn package sonar:sonar -Ddependencies.set.all -Dmaven.test.skip=true -Djavax.net.ssl.trustStore=${CACERTS} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings-ci.xml
  only:
    - master
  except:
    - tags

